### ISSUE TITLE
Array support doesn't work properly

### ISSUE THREAD

**Issue by NashBashor** [thiagolocatelli/parse4j#29]
Hello,
I tried the example for columns with type "Array" with the given example:

gameScore.addAllUnique("skills", Arrays.asList("flying", "kungfu"));
gameScore.saveInBackground();

And it throw me the exception: 
Exception in thread "main" java.lang.IllegalArgumentException: not implemented!
	at org.parse4j.operation.AddUniqueOperation.apply(AddUniqueOperation.java:27)
	at org.parse4j.ParseObject.performOperation(ParseObject.java:396)
	at org.parse4j.ParseObject.addAllUnique(ParseObject.java:331)

It seems that this feature is not implemented yet.

**Comment by GaurabAryal** [comment]
Irrelevant question: are you using libgdx by any chance? Thank you.

**Comment by NashBashor** [comment]
Nope, not in this parse4j project.

**Comment by GaurabAryal** [comment]
Oh, okay. Would you happen to know how i could possibly implement it in a libgdx project? I am having trouble. Sorry for hijacking your thread. Thank you once again.

**Comment by nickolayrusev** [comment]
hi, when i have a spare time ( may be this weekend) i will start to work on this issue.

**Comment by sadeceengin** [comment]
hey,
any progress on this issue?

**Comment by orioniota** [comment]
i got the same error
Any update?

**Comment by tomnof** [comment]
This thread is a bit old, but any chance there's something new?
