### ISSUE TITLE
ParseQuery and ParseObject with ParseFile

### ISSUE THREAD

**Issue by drmillan** [thiagolocatelli/parse4j#6]
Hello, I am trying to query a list of objects which contains a ParseFile, this is the failing code:
ParseQuery<ParseObject> query=ParseQuery.getQuery("file_test");
System.out.println(query.find().size());

I am getting this exception:
Exception in thread "main" java.lang.IllegalArgumentException: ParseFile must be saved before being set on a ParseObject.
    at org.parse4j.ParseObject.put(ParseObject.java:359)

Maybe find setData method should not be doing same validations as when we are creating the objects, I may be wrong on this :P

**Comment by StijnQ** [comment]
I'm also getting this error when trying to query ParseObjects that contain ParseFiles. Will this be fixed, or is there a another way to handle this?

**Comment by aguyngueran** [comment]
What I did for my project was to change:

	public ParseFile(String name, String url) {
		this.name = name;
		this.url = url;
	}

into this:

	public ParseFile(String name, String url) {
		this.name = name;
		this.url = url;
		this.dirty = false;
		this.uplodated = true;
	}

**Comment by StijnQ** [comment]
Thank you for the quick reply. Could you tell me how I can edit the parse4j.jar library like that?

**Comment by aguyngueran** [comment]
Personally, I have downloaded Parse4j sources and included it in my project.
As far as I remember there were few other changes to this library as well.

Best regards
    Rafał Grzybowski

**Comment by aperritano** [comment]
Hi, I'm having this same problem. Is there a better work around then changing the source? I'm using this library from a mvn jar.

i        ParseRelation<PItem> pItems = getRelation("PItems");
        ParseQuery<PItem> fetchQuery = pItems.getQuery();

        List<PItem> allPItems = null;
        try {
            allPItems = fetchQuery.find();
        } catch (ParseException e) {
            e.printStackTrace();
        }

Exception in thread "pool-1-thread-1" java.lang.IllegalArgumentException: ParseFile must be saved before being set on a ParseObject.
	at org.parse4j.ParseObject.put(ParseObject.java:359)
	at org.parse4j.ParseObject.setData(ParseObject.java:725)
	at org.parse4j.ParseQuery.find(ParseQuery.java:499)

why is it trying to set an object when I'm trying to do a query?
