### ISSUE TITLE
Crashing on query.whereContainedIn("pointer", listOfParseObjects);

### ISSUE THREAD

**Issue by edvardasast** [thiagolocatelli/parse4j#71]
`ParseQuery<ParseObject> query = new ParseQuery<ParseObject>("Table");
                        query.whereContainedIn("pointer", listOfParseObjects);
                        query.findInBackground(new FindCallback<ParseObject>() {
                            @Override
                            public void done(List<ParseObject> list, ParseException parseException) {
                                if (parseException == null) {
                                      //do something
                                    }}else{
                                    parseException.printStackTrace();
                                }
                            }
                        });`

Exception in thread "pool-1-thread-3" org.json.JSONException: A JSONObject text must begin with '{' at 1 [character 2 line 1]
    at org.json.JSONTokener.syntaxError(JSONTokener.java:451)
    at org.json.JSONObject.<init>(JSONObject.java:195)
    at org.json.JSONObject.<init>(JSONObject.java:319)
    at org.parse4j.command.ParseResponse.getJsonObject(ParseResponse.java:83)
    at org.parse4j.command.ParseResponse.getException(ParseResponse.java:71)
    at org.parse4j.ParseQuery.find(ParseQuery.java:598)
    at org.parse4j.ParseQuery.find(ParseQuery.java:469)
    at org.parse4j.ParseQuery$FindInBackgroundThread.run(ParseQuery.java:618)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)

**Comment by HdiaSaad** [comment]
i have the same probleme
