### ISSUE TITLE
Error saving object  "java.lang.IllegalArgumentException: not implemented!" 

### ISSUE THREAD

**Issue by eudson** [thiagolocatelli/parse4j#72]
I found this lib a few hours ago and i decided to test, but suddenly, when i try to save a object to my parse app i get the following error.  
Exception in thread "main" java.lang.IllegalArgumentException: not implemented!
    at org.parse4j.operation.AddOperation.apply(AddOperation.java:26)
    at org.parse4j.ParseObject.performOperation(ParseObject.java:396)
    at org.parse4j.ParseObject.addAll(ParseObject.java:322)
    at org.parse4j.ParseObject.add(ParseObject.java:317) 

I saw the source of the version 1.4 (the last on mvrepository) and i found that you are throwing the exception on purpose, there is anything that i can do to skip this error??

Thanks in advance.

**Comment by eudson** [comment]
I was using add instead of put. I'm sorry
